-- SYNAX Cloudflare/Supabase schema
-- Run this entire file once in Supabase SQL Editor for a NEW project.
-- The application uses the service-role key server-side; no key is exposed to the browser.

create table if not exists public.synax_state (
  id text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.synax_state enable row level security;

create table if not exists public.synax_sessions (
  token text primary key,
  user_id text not null check (user_id in ('person_1', 'person_2', 'admin')),
  session_start bigint not null,
  last_active bigint not null,
  allowed_seconds bigint not null,
  is_expired boolean not null default false,
  active boolean not null default false,
  ended_at bigint
);

create index if not exists synax_sessions_user_idx
  on public.synax_sessions (user_id, last_active desc);

alter table public.synax_sessions enable row level security;

create table if not exists public.synax_call_signals (
  id bigint generated by default as identity primary key,
  from_user_id text not null check (from_user_id in ('person_1', 'person_2')),
  target_user_id text not null check (target_user_id in ('person_1', 'person_2')),
  type text not null check (type like 'call:%'),
  call_type text check (call_type in ('voice', 'video')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists synax_call_signals_target_id_idx
  on public.synax_call_signals (target_user_id, id);

create index if not exists synax_call_signals_created_at_idx
  on public.synax_call_signals (created_at);

create index if not exists synax_call_signals_target_created_idx
  on public.synax_call_signals (target_user_id, created_at, id);

create index if not exists synax_call_signals_call_id_idx
  on public.synax_call_signals ((payload->>'callId'));

alter table public.synax_call_signals enable row level security;

-- Public upload bucket. The server uploads with the service-role key.
insert into storage.buckets (id, name, public)
values ('synax-uploads', 'synax-uploads', true)
on conflict (id) do update set public = true;


-- Canonical chat storage. Do NOT store the live conversation only in a Worker
-- global: Cloudflare Workers can use different isolates for different requests.
create table if not exists public.synax_messages (
  id text primary key,
  client_message_id text unique,
  sender_id text not null check (sender_id in ('person_1', 'person_2', 'system')),
  type text not null check (type in ('text', 'image', 'video', 'file', 'voice', 'system')),
  text text not null default '',
  file_url text,
  file_name text,
  file_size bigint,
  audio_duration numeric,
  timestamp bigint not null,
  status text not null default 'sent' check (status in ('sent', 'delivered', 'read')),
  reactions jsonb not null default '{}'::jsonb,
  reply_to jsonb,
  is_pinned boolean not null default false,
  is_edited boolean not null default false,
  deleted boolean not null default false
);

create index if not exists synax_messages_timestamp_idx
  on public.synax_messages (timestamp);

create index if not exists synax_messages_sender_status_idx
  on public.synax_messages (sender_id, status);

alter table public.synax_messages enable row level security;

-- Shared chat appearance. The background belongs to the private chat, not a device.
create table if not exists public.synax_chat_settings (
  chat_id text primary key,
  background_type text not null default 'preset' check (background_type in ('preset', 'image')),
  background_value text not null default 'stars',
  background_updated_at bigint not null default 0,
  updated_by text check (updated_by in ('person_1', 'person_2')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.synax_chat_settings enable row level security;

-- Canonical cross-isolate active-use timer and presence state.
create table if not exists public.synax_user_usage (
  user_id text primary key check (user_id in ('person_1', 'person_2')),
  continuous_used_seconds bigint not null default 0,
  daily_used_seconds bigint not null default 0,
  daily_usage_date text,
  active boolean not null default false,
  active_started_at bigint,
  last_heartbeat bigint not null default 0,
  last_seen bigint not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.synax_user_usage enable row level security;

-- Supabase projects created under the 2026 Data API defaults may not expose
-- newly-created public tables automatically. The Cloudflare Worker talks to
-- PostgREST using a server-side secret/service key, so grant that role the
-- required table/sequence privileges explicitly.
grant usage on schema public to service_role;
grant select, insert, update, delete on table
  public.synax_state,
  public.synax_sessions,
  public.synax_call_signals,
  public.synax_messages,
  public.synax_chat_settings,
  public.synax_user_usage
  to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Refresh PostgREST's schema cache after applying the migration.
notify pgrst, 'reload schema';


-- V36: migrate existing databases so video chat messages are valid.
alter table public.synax_messages
  drop constraint if exists synax_messages_type_check;

alter table public.synax_messages
  add constraint synax_messages_type_check
  check (type in ('text', 'image', 'video', 'file', 'voice', 'system'));

notify pgrst, 'reload schema';

-- V38: authoritative daily timer checkpoint + atomic midnight reset.
create or replace function public.synax_checkpoint_usage(
  p_user_id text,
  p_now_ms bigint,
  p_active boolean,
  p_today text,
  p_grace_ms bigint default 15000
)
returns public.synax_user_usage
language plpgsql
security definer
set search_path = public
as $$
declare
  usage_row public.synax_user_usage%rowtype;
  effective_end bigint;
  elapsed_seconds bigint := 0;
  grace_ms bigint := greatest(1000, least(coalesce(p_grace_ms, 15000), 60000));
begin
  if p_user_id not in ('person_1', 'person_2') then
    raise exception 'Invalid SYNAX user id';
  end if;

  insert into public.synax_user_usage (
    user_id, continuous_used_seconds, daily_used_seconds, daily_usage_date,
    active, active_started_at, last_heartbeat, last_seen, updated_at
  ) values (
    p_user_id, 0, 0, p_today, false, null, 0, 0, now()
  )
  on conflict (user_id) do nothing;

  select * into usage_row
  from public.synax_user_usage
  where user_id = p_user_id
  for update;

  if usage_row.active and usage_row.active_started_at is not null then
    effective_end := least(
      p_now_ms,
      coalesce(usage_row.last_heartbeat, usage_row.active_started_at) + grace_ms
    );
    elapsed_seconds := greatest(0, floor((effective_end - usage_row.active_started_at) / 1000.0));
    usage_row.daily_used_seconds := greatest(
      0,
      coalesce(usage_row.daily_used_seconds, 0) + elapsed_seconds
    );
  end if;

  if p_active then
    usage_row.active := true;
    usage_row.active_started_at := p_now_ms;
    usage_row.last_heartbeat := p_now_ms;
  else
    usage_row.active := false;
    usage_row.active_started_at := null;
    usage_row.last_heartbeat := p_now_ms;
    usage_row.last_seen := p_now_ms;
  end if;

  usage_row.updated_at := now();

  update public.synax_user_usage
  set
    continuous_used_seconds = usage_row.continuous_used_seconds,
    daily_used_seconds = usage_row.daily_used_seconds,
    daily_usage_date = usage_row.daily_usage_date,
    active = usage_row.active,
    active_started_at = usage_row.active_started_at,
    last_heartbeat = usage_row.last_heartbeat,
    last_seen = usage_row.last_seen,
    updated_at = usage_row.updated_at
  where user_id = p_user_id;

  return usage_row;
end;
$$;

grant execute on function public.synax_checkpoint_usage(text, bigint, boolean, text, bigint) to service_role;

create or replace function public.synax_reset_daily_usage(
  p_reset_date text,
  p_reset_at_ms bigint
)
returns setof public.synax_user_usage
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.synax_user_usage%rowtype;
  current_heartbeat bigint;
begin
  for r in
    select * from public.synax_user_usage
    where user_id in ('person_1', 'person_2')
    order by user_id
    for update
  loop
    current_heartbeat := coalesce(r.last_heartbeat, 0);
    r.continuous_used_seconds := 0;
    r.daily_used_seconds := 0;
    r.daily_usage_date := p_reset_date;

    if r.active
       and current_heartbeat > 0
       and current_heartbeat >= p_reset_at_ms - 15000
       and current_heartbeat <= p_reset_at_ms + 15000 then
      r.active := true;
      r.active_started_at := p_reset_at_ms;
    else
      r.active := false;
      r.active_started_at := null;
      if current_heartbeat > 0 then
        r.last_seen := current_heartbeat;
      end if;
    end if;

    r.updated_at := now();

    update public.synax_user_usage
    set
      continuous_used_seconds = r.continuous_used_seconds,
      daily_used_seconds = r.daily_used_seconds,
      daily_usage_date = r.daily_usage_date,
      active = r.active,
      active_started_at = r.active_started_at,
      last_heartbeat = r.last_heartbeat,
      last_seen = r.last_seen,
      updated_at = r.updated_at
    where user_id = r.user_id;

    return next r;
  end loop;
end;
$$;

grant execute on function public.synax_reset_daily_usage(text, bigint) to service_role;

notify pgrst, 'reload schema';
